### ISSUE TITLE
No styles being applied, using with storybook, next js and tailwindcss

### ISSUE THREAD

**Issue by SidRathi47** [vechai/vechaiui#47]
Hi I loved this library but sadly the styles don't seem to work.
here is my config 

```js

module.exports = {
  mode: 'jit',
  purge: [
    "./node_modules/@vechaiui/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./stories/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class", // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require("@tailwindcss/forms"), require("@vechaiui/core")],
};


```

**Comment by SidRathi47** [comment]
ahh figured it out, read your storybook folder code. I am still new to storybook. By the way, if you would like a hand with the development/documentation of vechai let me know. I really wanted to make something like this as I love tailwindcss. But because this already exists, I want to contribute. 

I would love to have a chat even for 5 mins will do!! please 
here is my Instagram 
https://www.instagram.com/sid_web_works/

**Comment by pepelele** [comment]
Do you mean the components that don't work with primary colors?

Yeah, I'm using vechaiui to build my side project and it's enough components for me... But I'm planning to add more components and redesign the document to be ready to publish v1.I'm also working on a vechai blocks package (copy/paste component for marketing page) but I don't have time yet... I'm happy if you want to help but I don't know how to start.

Sorry but, I use twitter instead of Instagram https://twitter.com/TrnBThanhTng1 ... Let's DM me if you want

**Comment by SidRathi47** [comment]
Yeah sure would love to contribute to that! I have some experience in designing using Figma and stuff. And I know React, Next etc., still learning typescript tho lol.

Cool, I actually just followed you, though I am unable to DM u IDK why. let me know if u can dm me. I don't know how to use Twitter lol. just enabled my account to talk to you.
https://twitter.com/sid_web_works

**Comment by SidRathi47** [comment]
And yes I managed to fix that color issue, I had to add those colors in the plugin options array. Not sure why we do that tho.
